### ISSUE TITLE
一次回复的消息不完整

### ISSUE THREAD

**Issue by xufengnian** [HuXioAn/GPT-Lark#2]
老哥，由于chatgpt自身原因，一次回复消息是不全的，导致回复的内容长一点不够完整，是不是可以增加等待时间等消息全一点再回复？

**Comment by xufengnian** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/15324125/221362863-a3ceeb0f-8aa4-427e-aa3b-09e264d3472b.png">

**Comment by HuXioAn** [comment]
程序里我将Max token 设置为256，这里应该是达到上限了，可以更改文件里的数值，或者下一版，我把这个值添加到配置文件里。

**Comment by HuXioAn** [comment]
16行，self.maxToken=256

**Comment by xufengnian** [comment]
@HuXioAn 感谢老哥，我也查了一下官方文档对于openai.Completion.create这个API的参数说明，分别测试了改成1024及2048，回复内容确实增加了，等待时长也相应增加，不过这个在预期之内，多谢！
![image](https://user-images.githubusercontent.com/15324125/221451364-8dbbd79e-218f-4abd-9591-f8086292cc34.png)
![image](https://user-images.githubusercontent.com/15324125/221451443-cdddeae3-73d8-4562-9e2b-46101bc12c1d.png)
