### ISSUE TITLE
老哥，现在国内服务器应该用不了吧

### ISSUE THREAD

**Issue by xufengnian** [HuXioAn/GPT-Lark#3]
我看3.2起，api.openai.com这个域名已经被墙了，所以很难获取到信息了

**Comment by HuXioAn** [comment]
确实，前天我用腾讯云上海测试了，不能用。也可能是因为开会。

**Comment by xufengnian** [comment]
完全有可能，我这边目前用的是腾讯云香港，还可以正常使用，已经做好了国内开完会也不能用的准备了
