### ISSUE TITLE
机器人不回复

### ISSUE THREAD

**Issue by lengyue1** [HuXioAn/GPT-Lark#5]
![图片](https://user-images.githubusercontent.com/63763765/230717136-2bfdf61a-008f-4f62-80bc-f0a192ca160d.png)
机器人发送欢迎消息后，其他消息不回复

**Comment by HuXioAn** [comment]
可以提供终端输出的调试信息吗？
可以捡查一下配置文件。

发自我的 iPad

在 2023年4月8日，18:48，lengyue1 ***@***.***> 写道：

﻿

[图片]<https://user-images.githubusercontent.com/63763765/230717136-2bfdf61a-008f-4f62-80bc-f0a192ca160d.png>
机器人发送欢迎消息后，其他消息不回复

**Comment by lengyue1** [comment]
终端存在报错，我用python3.9跑的，不知是不是python版本问题




1936744764
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuXioAn/GPT-Lark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuXioAn/GPT-Lark] 机器人不回复 (Issue #5)





 可以提供终端输出的调试信息吗？ 
 可以捡查一下配置文件。 
 
 发自我的 iPad 
 
 在 2023年4月8日，18:48，lengyue1 ***@***.***&gt; 写道： 
 
 ﻿ 
 
 [图片]<https://user-images.githubusercontent.com/63763765/230717136-2bfdf61a-008f-4f62-80bc-f0a192ca160d.png&gt; 
 机器人发送欢迎消息后，其他消息不回复

**Comment by HuXioAn** [comment]
可以让我看一下输出吗？

**Comment by lengyue1** [comment]
这是回复的



1936744764
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuXioAn/GPT-Lark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuXioAn/GPT-Lark] 机器人不回复 (Issue #5)





 
可以让我看一下输出吗？

**Comment by HuXioAn** [comment]
是我的显示有问题吗？我看不到输出内容。只有：
[1936744764](tel:1936744764)
***@***.***

**Comment by lengyue1** [comment]
放附件里了，在看下呢



1936744764
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuXioAn/GPT-Lark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuXioAn/GPT-Lark] 机器人不回复 (Issue #5)





 
是我的显示有问题吗？我看不到输出内容。只有：
 1936744764
 @.***

**Comment by HuXioAn** [comment]
我好像看不到有附件🥹

**Comment by lengyue1** [comment]
啊，要不加个QQ或者微信?



1936744764
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuXioAn/GPT-Lark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuXioAn/GPT-Lark] 机器人不回复 (Issue #5)





 
我好像看不到有附件🥹
